### ISSUE TITLE
NodeJs

### ISSUE THREAD

**Issue by alfredudu** [UeiRicho/cgi-node#11]
I believe that due to the path that your have, in my not have such access could help me?

Thanks

I need NodeJs on My Godaddy Share Server

**Comment by deda-ca** [comment]
I'd be more than happy to help, but can you be more specific as to what issues or errors you are getting.

**Comment by alfredudu** [comment]
Thank you, unfortunately I will have exchange to another  framework is not necessary the use of nodejs .

Thank you
