### ISSUE TITLE
maybe a typo

### ISSUE THREAD

**Issue by dotme** [UeiRicho/cgi-node#31]
Hello.
It is normal that **EndTag** is **'<?'** instead **'?>'**? Sorry if I have missunderstand something.
Have a nice day.

**Comment by AlexisWilke** [comment]
The EndTag is wrong in the `CgiNodeConfig` definition:

    var CgiNodeConfig = 
    {
        Version: '0.2',

        StartTag: '<?',
        EndTag: '<?',    // <- here, should be '?>'

        ScriptExtensions: ['.js'],

        EmbededScriptExtensions: ['.jss'],


        SessionCookie: 'CGI-NODE-SESSIONID',
        SessionTimeOut: 15*60, // 15 minutes
        SessionPath: '/var/lib/cgi-node'
    };

Note that at this point those two configuration parameters are not used. If you search the source, you will see:

    script : function(id, path, content)
    {
        // Set the optional parameters to the default values.
        // TODO: get these from the configuration object.
        var openTag = '<?';
        var closeTag = '?>';
        [...snip...]

So it will work as expected, only it is definitely confusing.

**Comment by dotme** [comment]
My mistake
